use gisVDT;

create extension postgis;

create table ship(
	id TEXT PRIMARY KEY
);

create table ship_radar_info(
	id integer primary key generated by default as identity,
	coordinate geography(POINT) not null,
	speed real not null,
	angle real not null,
	timestamp timestamp not null,
	ship_id text,
	constraint fk_shipId foreign key (ship_id) references ship(id) 
);
